name: Foundation CI Checks

on:
  push:
    branches: [ main, develop ]
  pull_request:
    branches: [ main, develop ]
    paths:
      - "**/*.html"
      - "**/*.js"
      - "**/*.json"
      - "**/*.md"
      - ".htaccess"
      - "_redirects"
      - "sitemap.xml"
      - "robots.txt"

jobs:
  forms:
    name: Form Validation Check
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        
      - name: Make scripts executable
        run: chmod +x scripts/validate-forms.sh
        
      - name: Validate forms
        run: ./scripts/validate-forms.sh
        
      - name: Form validation summary
        if: always()
        run: |
          echo "## 📋 Form Validation Results" >> $GITHUB_STEP_SUMMARY
          if [ $? -eq 0 ]; then
            echo "✅ All forms pass validation checks" >> $GITHUB_STEP_SUMMARY
          else
            echo "❌ Form validation issues found" >> $GITHUB_STEP_SUMMARY
          fi

  tos:
    name: Terms of Service Check
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        
      - name: Make scripts executable
        run: chmod +x scripts/check-tos-exists.sh
        
      - name: Check Terms of Service
        run: ./scripts/check-tos-exists.sh
        
      - name: ToS check summary
        if: always()
        run: |
          echo "## 📋 Terms of Service Results" >> $GITHUB_STEP_SUMMARY
          if [ $? -eq 0 ]; then
            echo "✅ Terms of Service properly configured" >> $GITHUB_STEP_SUMMARY
          else
            echo "❌ Terms of Service issues found" >> $GITHUB_STEP_SUMMARY
          fi

  urls:
    name: Clean URLs Check
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        
      - name: Make scripts executable
        run: chmod +x scripts/check-clean-urls.sh
        
      - name: Check clean URLs
        run: ./scripts/check-clean-urls.sh
        
      - name: Clean URLs summary
        if: always()
        run: |
          echo "## 🌐 Clean URLs Results" >> $GITHUB_STEP_SUMMARY
          if [ $? -eq 0 ]; then
            echo "✅ Clean URL structure properly configured" >> $GITHUB_STEP_SUMMARY
          else
            echo "❌ Clean URL issues found" >> $GITHUB_STEP_SUMMARY
          fi

  email-guard:
    name: Email Consistency Check
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        
      - name: Install ripgrep
        run: |
          curl -LO https://github.com/BurntSushi/ripgrep/releases/download/13.0.0/ripgrep_13.0.0_amd64.deb
          sudo dpkg -i ripgrep_13.0.0_amd64.deb
        
      - name: Block old emails
        run: |
          set -e
          echo "🔍 Checking for old email patterns..."
          if rg -n 'support@|contact@|info@|admin@|hello@' \
            --glob '!{.git,node_modules,dist,build,coverage,handoff}/**' \
            .; then
            echo "❌ Found old emails"
            exit 1
          else
            echo "✅ No old email patterns found"
          fi
          
      - name: Require deals@ email
        run: |
          echo "📧 Checking for required deals@ email..."
          if rg -n 'mailto:deals@dealradarus\.com' --type html . >/dev/null; then
            echo "✅ Found mailto:deals@ links"
          else
            echo "❌ No mailto:deals@ found"
            exit 1
          fi
          
      - name: Email check summary
        if: always()
        run: |
          echo "## 📧 Email Consistency Results" >> $GITHUB_STEP_SUMMARY
          if [ $? -eq 0 ]; then
            echo "✅ Email consistency maintained" >> $GITHUB_STEP_SUMMARY
          else
            echo "❌ Email consistency issues found" >> $GITHUB_STEP_SUMMARY
          fi

  seo-validation:
    name: SEO Structure Check
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        
      - name: Validate sitemap.xml
        run: |
          echo "🗺️  Validating sitemap.xml structure..."
          
          if [ ! -f "sitemap.xml" ]; then
            echo "❌ sitemap.xml not found"
            exit 1
          fi
          
          # Check XML syntax
          if ! xmllint --noout sitemap.xml 2>/dev/null; then
            echo "❌ sitemap.xml has invalid XML syntax"
            exit 1
          fi
          
          # Count URLs
          URL_COUNT=$(grep -c "<loc>" sitemap.xml)
          echo "✅ Found $URL_COUNT URLs in sitemap"
          
          if [ $URL_COUNT -lt 5 ]; then
            echo "⚠️  Sitemap has fewer than 5 URLs"
          fi
          
      - name: Validate robots.txt
        run: |
          echo "🤖 Validating robots.txt..."
          
          if [ ! -f "robots.txt" ]; then
            echo "❌ robots.txt not found"
            exit 1
          fi
          
          # Check required directives
          if ! grep -q "User-agent:" robots.txt; then
            echo "❌ robots.txt missing User-agent directive"
            exit 1
          fi
          
          if ! grep -q "Sitemap:" robots.txt; then
            echo "❌ robots.txt missing Sitemap directive"
            exit 1
          fi
          
          echo "✅ robots.txt structure valid"
          
      - name: Check meta tags
        run: |
          echo "🏷️  Checking essential meta tags..."
          
          HTML_FILES=("index.html" "pages/contact.html" "pages/terms-of-service.html")
          ISSUES=0
          
          for file in "${HTML_FILES[@]}"; do
            if [ -f "$file" ]; then
              echo "📄 Checking: $file"
              
              if ! grep -q "<title>" "$file"; then
                echo "❌ $file missing title tag"
                ISSUES=$((ISSUES + 1))
              fi
              
              if ! grep -q 'name="description"' "$file"; then
                echo "❌ $file missing meta description"
                ISSUES=$((ISSUES + 1))
              fi
              
              if ! grep -q 'name="viewport"' "$file"; then
                echo "❌ $file missing viewport meta"
                ISSUES=$((ISSUES + 1))
              fi
            fi
          done
          
          if [ $ISSUES -eq 0 ]; then
            echo "✅ All meta tags present"
          else
            echo "❌ Found $ISSUES meta tag issues"
            exit 1
          fi
          
      - name: SEO validation summary
        if: always()
        run: |
          echo "## 🔍 SEO Structure Results" >> $GITHUB_STEP_SUMMARY
          if [ $? -eq 0 ]; then
            echo "✅ SEO structure validation passed" >> $GITHUB_STEP_SUMMARY
          else
            echo "❌ SEO structure issues found" >> $GITHUB_STEP_SUMMARY
          fi

  summary:
    name: CI Summary
    runs-on: ubuntu-latest
    needs: [forms, tos, urls, email-guard, seo-validation]
    if: always()
    
    steps:
      - name: Generate overall summary
        run: |
          echo "# 🎯 Foundation CI Results Summary" >> $GITHUB_STEP_SUMMARY
          echo "" >> $GITHUB_STEP_SUMMARY
          echo "| Check | Status |" >> $GITHUB_STEP_SUMMARY
          echo "|-------|--------|" >> $GITHUB_STEP_SUMMARY
          
          # Forms check
          if [ "${{ needs.forms.result }}" == "success" ]; then
            echo "| 📋 Form Validation | ✅ Passed |" >> $GITHUB_STEP_SUMMARY
          else
            echo "| 📋 Form Validation | ❌ Failed |" >> $GITHUB_STEP_SUMMARY
          fi
          
          # ToS check
          if [ "${{ needs.tos.result }}" == "success" ]; then
            echo "| 📋 Terms of Service | ✅ Passed |" >> $GITHUB_STEP_SUMMARY
          else
            echo "| 📋 Terms of Service | ❌ Failed |" >> $GITHUB_STEP_SUMMARY
          fi
          
          # URLs check
          if [ "${{ needs.urls.result }}" == "success" ]; then
            echo "| 🌐 Clean URLs | ✅ Passed |" >> $GITHUB_STEP_SUMMARY
          else
            echo "| 🌐 Clean URLs | ❌ Failed |" >> $GITHUB_STEP_SUMMARY
          fi
          
          # Email check
          if [ "${{ needs.email-guard.result }}" == "success" ]; then
            echo "| 📧 Email Consistency | ✅ Passed |" >> $GITHUB_STEP_SUMMARY
          else
            echo "| 📧 Email Consistency | ❌ Failed |" >> $GITHUB_STEP_SUMMARY
          fi
          
          # SEO check
          if [ "${{ needs.seo-validation.result }}" == "success" ]; then
            echo "| 🔍 SEO Structure | ✅ Passed |" >> $GITHUB_STEP_SUMMARY
          else
            echo "| 🔍 SEO Structure | ❌ Failed |" >> $GITHUB_STEP_SUMMARY
          fi
          
          echo "" >> $GITHUB_STEP_SUMMARY
          echo "**Next Steps:**" >> $GITHUB_STEP_SUMMARY
          echo "- ✅ All checks passed: Ready for production deployment" >> $GITHUB_STEP_SUMMARY
          echo "- ❌ Issues found: Review failed checks and fix before merging" >> $GITHUB_STEP_SUMMARY