name: Email Guard
on:
  pull_request:
    paths:
      - "**/*.html"
      - "**/*.js"
      - "**/*.json"
      - "**/*.md"
jobs:
  guard:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Block old emails
        run: |
          set -e
          rg -n 'support@|contact@|info@|admin@|hello@' \
            --glob '!{.git,node_modules,dist,build,coverage,handoff}/**' \
            && { echo "❌ Found old emails"; exit 1; } || echo "✅ Clean"
      - name: Require deals@
        run: |
          rg -n 'mailto:deals@dealradarus\.com' --type html >/dev/null \
            || { echo "❌ No mailto:deals@ found"; exit 1; }