name: GA4 ID Validation

on:
  push:
    branches: [ main, develop ]
  pull_request:
    branches: [ main ]

jobs:
  validate-ga4-ids:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout repository
      uses: actions/checkout@v4
      
    - name: Check for unauthorized GA4 IDs
      run: |
        echo "🔍 Checking for GA4 tracking IDs in HTML files..."
        
        # Search for any GA4 measurement IDs (G-XXXXXXXXXX format)
        GA4_IDS=$(grep -rn "G-[A-Z0-9]\{10\}" --include="*.html" . || true)
        
        if [ -z "$GA4_IDS" ]; then
          echo "❌ No GA4 tracking IDs found in HTML files"
          exit 1
        fi
        
        echo "📋 Found GA4 IDs:"
        echo "$GA4_IDS"
        echo ""
        
        # Check if any unauthorized GA4 IDs exist (anything other than G-9ZVTTTBD03)
        UNAUTHORIZED_IDS=$(echo "$GA4_IDS" | grep -v "G-9ZVTTTBD03" || true)
        
        if [ -n "$UNAUTHORIZED_IDS" ]; then
          echo "❌ UNAUTHORIZED GA4 IDs detected:"
          echo "$UNAUTHORIZED_IDS"
          echo ""
          echo "🚨 Only G-9ZVTTTBD03 is allowed. Please remove any other GA4 tracking IDs."
          exit 1
        fi
        
        # Verify that G-9ZVTTTBD03 exists
        AUTHORIZED_COUNT=$(echo "$GA4_IDS" | grep "G-9ZVTTTBD03" | wc -l)
        
        if [ "$AUTHORIZED_COUNT" -eq 0 ]; then
          echo "❌ Authorized GA4 ID (G-9ZVTTTBD03) not found"
          exit 1
        fi
        
        echo "✅ GA4 ID validation passed!"
        echo "📊 Found $AUTHORIZED_COUNT instances of authorized GA4 ID: G-9ZVTTTBD03"
        
    - name: Check for GA4 duplicate load guard
      run: |
        echo "🛡️ Checking for GA4 duplicate load guards..."
        
        GUARD_COUNT=$(grep -r "__GA4_LOADED__" --include="*.html" . | wc -l)
        GA4_CONFIG_COUNT=$(grep -r "gtag.*config.*G-9ZVTTTBD03" --include="*.html" . | wc -l)
        
        echo "🔢 GA4 duplicate guards found: $GUARD_COUNT"
        echo "🔢 GA4 config instances found: $GA4_CONFIG_COUNT"
        
        if [ "$GUARD_COUNT" -ne "$GA4_CONFIG_COUNT" ]; then
          echo "⚠️ Warning: Not all GA4 configs have duplicate load guards"
          echo "Expected: $GA4_CONFIG_COUNT guards, Found: $GUARD_COUNT guards"
        else
          echo "✅ All GA4 configs are properly protected with duplicate load guards"
        fi